//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace MGRE.ETL.Contracts.DataContracts
{
    /*
    internal partial class DualAppShortcutSetting
    {
        #region Primitive Properties
    
        [DataMember]
        public int AppID
        {
            get;
            set;
        }
    
        [DataMember]
        public string WindowTitle
        {
            get;
            set;
        }
    
        [DataMember]
        public string WindowBackgroundColour
        {
            get;
            set;
        }
    
        [DataMember]
        public string WindowBorderColor
        {
            get;
            set;
        }
    
        [DataMember]
        public string PrimeButtonBackgroundColor
        {
            get;
            set;
        }
    
        [DataMember]
        public string HeaderTextColor
        {
            get;
            set;
        }
    
        [DataMember]
        public string PrimeTextColor
        {
            get;
            set;
        }
    
        [DataMember]
        public string YardiTextColor
        {
            get;
            set;
        }
    
        [DataMember]
        public string HeaderText
        {
            get;
            set;
        }
    
        [DataMember]
        public string PrimeButtonText
        {
            get;
            set;
        }
    
        [DataMember]
        public string YardiButtonText
        {
            get;
            set;
        }
    
        [DataMember]
        public string YardiButtonBackgroundColor
        {
            get;
            set;
        }
    
        [DataMember]
        public bool YardiButtonEnabled
        {
            get;
            set;
        }
    
        [DataMember]
        public bool PrimeButtonEnabled
        {
            get;
            set;
        }

        #endregion
    
    }
    */
}
