//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace MGRE.ETL.Contracts.DataContracts
{
    /*
    internal partial class ETLExportSchedule
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid ETLExportGUID
        {
            get;
            set;
        }
    
        [DataMember]
        public System.DateTime ETLExportStartDate
        {
            get;
            set;
        }
    
        [DataMember]
        public int ETLExportPeriodicity
        {
            get { return _eTLExportPeriodicity; }
            set
            {
                if (_eTLExportPeriodicity != value)
                {
                    if (ETLPeriodicity != null && ETLPeriodicity.PeriodID != value)
                    {
                        ETLPeriodicity = null;
                    }
                    _eTLExportPeriodicity = value;
                }
            }
        }
        private int _eTLExportPeriodicity;
    
        [DataMember]
        public System.TimeSpan ETLTime1
        {
            get;
            set;
        }
    
        [DataMember]
        public Nullable<System.TimeSpan> ETLTime2
        {
            get;
            set;
        }
    
        [DataMember]
        public Nullable<System.TimeSpan> ETLTime3
        {
            get;
            set;
        }
    
        [DataMember]
        public Nullable<System.TimeSpan> ETLTime4
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ETLExportDefinition ETLExportDefinition
        {
            get { return _eTLExportDefinition; }
            set
            {
                if (!ReferenceEquals(_eTLExportDefinition, value))
                {
                    var previousValue = _eTLExportDefinition;
                    _eTLExportDefinition = value;
                    FixupETLExportDefinition(previousValue);
                }
            }
        }
        private ETLExportDefinition _eTLExportDefinition;
    
        public virtual ETLPeriodicity ETLPeriodicity
        {
            get { return _eTLPeriodicity; }
            set
            {
                if (!ReferenceEquals(_eTLPeriodicity, value))
                {
                    var previousValue = _eTLPeriodicity;
                    _eTLPeriodicity = value;
                    FixupETLPeriodicity(previousValue);
                }
            }
        }
        private ETLPeriodicity _eTLPeriodicity;

        #endregion
        #region Association Fixup
    
        private void FixupETLExportDefinition(ETLExportDefinition previousValue)
        {
            if (previousValue != null && ReferenceEquals(previousValue.ETLExportSchedule, this))
            {
                previousValue.ETLExportSchedule = null;
            }
    
            if (ETLExportDefinition != null)
            {
                ETLExportDefinition.ETLExportSchedule = this;
            }
        }
    
        private void FixupETLPeriodicity(ETLPeriodicity previousValue)
        {
            if (previousValue != null && previousValue.ETLExportSchedules.Contains(this))
            {
                previousValue.ETLExportSchedules.Remove(this);
            }
    
            if (ETLPeriodicity != null)
            {
                if (!ETLPeriodicity.ETLExportSchedules.Contains(this))
                {
                    ETLPeriodicity.ETLExportSchedules.Add(this);
                }
                if (ETLExportPeriodicity != ETLPeriodicity.PeriodID)
                {
                    ETLExportPeriodicity = ETLPeriodicity.PeriodID;
                }
            }
        }

        #endregion
    
    }
    */
}
