//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace MGRE.ETL.Contracts.DataContracts
{
    /*
    internal partial class ETLImportHistory
    {
        #region Primitive Properties
    
        [DataMember]
        public System.Guid ETLImportHistoryGUID
        {
            get;
            set;
        }
    
        [DataMember]
        public System.Guid ETLImportGUID
        {
            get { return _eTLImportGUID; }
            set
            {
                if (_eTLImportGUID != value)
                {
                    if (ETLImportDefinition != null && ETLImportDefinition.ETLImportGUID != value)
                    {
                        ETLImportDefinition = null;
                    }
                    _eTLImportGUID = value;
                }
            }
        }
        private System.Guid _eTLImportGUID;
    
        [DataMember]
        public System.DateTime ETLImportDate
        {
            get;
            set;
        }
    
        [DataMember]
        public string ETLImportSubmittedBy
        {
            get;
            set;
        }
    
        [DataMember]
        public System.DateTime ETLImportStartDate
        {
            get;
            set;
        }
    
        [DataMember]
        public System.DateTime ETLImportEndDate
        {
            get;
            set;
        }
    
        [DataMember]
        public int Status
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ETLImportDefinition ETLImportDefinition
        {
            get { return _eTLImportDefinition; }
            set
            {
                if (!ReferenceEquals(_eTLImportDefinition, value))
                {
                    var previousValue = _eTLImportDefinition;
                    _eTLImportDefinition = value;
                    FixupETLImportDefinition(previousValue);
                }
            }
        }
        private ETLImportDefinition _eTLImportDefinition;

        #endregion
        #region Association Fixup
    
        private void FixupETLImportDefinition(ETLImportDefinition previousValue)
        {
            if (previousValue != null && previousValue.ETLImportHistories.Contains(this))
            {
                previousValue.ETLImportHistories.Remove(this);
            }
    
            if (ETLImportDefinition != null)
            {
                if (!ETLImportDefinition.ETLImportHistories.Contains(this))
                {
                    ETLImportDefinition.ETLImportHistories.Add(this);
                }
                if (ETLImportGUID != ETLImportDefinition.ETLImportGUID)
                {
                    ETLImportGUID = ETLImportDefinition.ETLImportGUID;
                }
            }
        }

        #endregion
    
    }
    */
}
