//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;


namespace MGRE.ETL.Contracts.DataContracts
{
    /*
    internal partial class vw_FundsAndProperties
    {
        #region Primitive Properties
    
        [DataMember]
        public string ID
        {
            get;
            set;
        }
    
        [DataMember]
        public string Name
        {
            get;
            set;
        }
    
        [DataMember]
        public bool Migrated
        {
            get;
            set;
        }

        #endregion
    
    }
    */
}
