//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MGRE.ETL.Data
{
    public partial class DualAppShortcutSetting
    {
        #region Primitive Properties
    
        public virtual int AppID
        {
            get;
            set;
        }
    
        public virtual string WindowTitle
        {
            get;
            set;
        }
    
        public virtual string WindowBackgroundColour
        {
            get;
            set;
        }
    
        public virtual string WindowBorderColor
        {
            get;
            set;
        }
    
        public virtual string PrimeButtonBackgroundColor
        {
            get;
            set;
        }
    
        public virtual string HeaderTextColor
        {
            get;
            set;
        }
    
        public virtual string PrimeTextColor
        {
            get;
            set;
        }
    
        public virtual string YardiTextColor
        {
            get;
            set;
        }
    
        public virtual string HeaderText
        {
            get;
            set;
        }
    
        public virtual string PrimeButtonText
        {
            get;
            set;
        }
    
        public virtual string YardiButtonText
        {
            get;
            set;
        }
    
        public virtual string YardiButtonBackgroundColor
        {
            get;
            set;
        }
    
        public virtual bool YardiButtonEnabled
        {
            get;
            set;
        }
    
        public virtual bool PrimeButtonEnabled
        {
            get;
            set;
        }

        #endregion
    }
}
