//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;


namespace MGRE.ETL.Data
{
    public partial class ETLEntities : ObjectContext
    {
        public const string ConnectionString = "name=ETLEntities";
        public const string ContainerName = "ETLEntities";
    
        #region Constructors
    
        public ETLEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ETLEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public ETLEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<ETLExportConfiguration> ETLExportConfigurations
        {
            get { return _eTLExportConfigurations  ?? (_eTLExportConfigurations = CreateObjectSet<ETLExportConfiguration>("ETLExportConfigurations")); }
        }
        private ObjectSet<ETLExportConfiguration> _eTLExportConfigurations;
    
        public ObjectSet<ETLExportDefinition> ETLExportDefinitions
        {
            get { return _eTLExportDefinitions  ?? (_eTLExportDefinitions = CreateObjectSet<ETLExportDefinition>("ETLExportDefinitions")); }
        }
        private ObjectSet<ETLExportDefinition> _eTLExportDefinitions;
    
        public ObjectSet<ETLExportHistory> ETLExportHistories
        {
            get { return _eTLExportHistories  ?? (_eTLExportHistories = CreateObjectSet<ETLExportHistory>("ETLExportHistories")); }
        }
        private ObjectSet<ETLExportHistory> _eTLExportHistories;
    
        public ObjectSet<ETLExportSchedule> ETLExportSchedules
        {
            get { return _eTLExportSchedules  ?? (_eTLExportSchedules = CreateObjectSet<ETLExportSchedule>("ETLExportSchedules")); }
        }
        private ObjectSet<ETLExportSchedule> _eTLExportSchedules;
    
        public ObjectSet<ETLExportTablesDefinition> ETLExportTablesDefinitions
        {
            get { return _eTLExportTablesDefinitions  ?? (_eTLExportTablesDefinitions = CreateObjectSet<ETLExportTablesDefinition>("ETLExportTablesDefinitions")); }
        }
        private ObjectSet<ETLExportTablesDefinition> _eTLExportTablesDefinitions;
    
        public ObjectSet<ETLPeriodicity> ETLPeriodicities
        {
            get { return _eTLPeriodicities  ?? (_eTLPeriodicities = CreateObjectSet<ETLPeriodicity>("ETLPeriodicities")); }
        }
        private ObjectSet<ETLPeriodicity> _eTLPeriodicities;
    
        public ObjectSet<ETLExportEmail> ETLExportEmails
        {
            get { return _eTLExportEmails  ?? (_eTLExportEmails = CreateObjectSet<ETLExportEmail>("ETLExportEmails")); }
        }
        private ObjectSet<ETLExportEmail> _eTLExportEmails;
    
        public ObjectSet<ETLImportConfiguration> ETLImportConfigurations
        {
            get { return _eTLImportConfigurations  ?? (_eTLImportConfigurations = CreateObjectSet<ETLImportConfiguration>("ETLImportConfigurations")); }
        }
        private ObjectSet<ETLImportConfiguration> _eTLImportConfigurations;
    
        public ObjectSet<ETLImportDefinition> ETLImportDefinitions
        {
            get { return _eTLImportDefinitions  ?? (_eTLImportDefinitions = CreateObjectSet<ETLImportDefinition>("ETLImportDefinitions")); }
        }
        private ObjectSet<ETLImportDefinition> _eTLImportDefinitions;
    
        public ObjectSet<ETLImportEmail> ETLImportEmails
        {
            get { return _eTLImportEmails  ?? (_eTLImportEmails = CreateObjectSet<ETLImportEmail>("ETLImportEmails")); }
        }
        private ObjectSet<ETLImportEmail> _eTLImportEmails;
    
        public ObjectSet<ETLImportHistory> ETLImportHistories
        {
            get { return _eTLImportHistories  ?? (_eTLImportHistories = CreateObjectSet<ETLImportHistory>("ETLImportHistories")); }
        }
        private ObjectSet<ETLImportHistory> _eTLImportHistories;
    
        public ObjectSet<ETLImportTablesDefinition> ETLImportTablesDefinitions
        {
            get { return _eTLImportTablesDefinitions  ?? (_eTLImportTablesDefinitions = CreateObjectSet<ETLImportTablesDefinition>("ETLImportTablesDefinitions")); }
        }
        private ObjectSet<ETLImportTablesDefinition> _eTLImportTablesDefinitions;
    
        public ObjectSet<DualAppShortcutSetting> DualAppShortcutSettings
        {
            get { return _dualAppShortcutSettings  ?? (_dualAppShortcutSettings = CreateObjectSet<DualAppShortcutSetting>("DualAppShortcutSettings")); }
        }
        private ObjectSet<DualAppShortcutSetting> _dualAppShortcutSettings;
    
        public ObjectSet<vw_FundsAndProperties> vw_FundsAndProperties
        {
            get { return _vw_FundsAndProperties  ?? (_vw_FundsAndProperties = CreateObjectSet<vw_FundsAndProperties>("vw_FundsAndProperties")); }
        }
        private ObjectSet<vw_FundsAndProperties> _vw_FundsAndProperties;

        #endregion
    }
}
