//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace MGRE.ETL.Data
{
    public partial class ETLImportEmail
    {
        #region Primitive Properties
    
        public virtual System.Guid ETLEmailGUID
        {
            get;
            set;
        }
    
        public virtual System.Guid ETLImportGUID
        {
            get { return _eTLImportGUID; }
            set
            {
                if (_eTLImportGUID != value)
                {
                    if (ETLImportDefinition != null && ETLImportDefinition.ETLImportGUID != value)
                    {
                        ETLImportDefinition = null;
                    }
                    _eTLImportGUID = value;
                }
            }
        }
        private System.Guid _eTLImportGUID;
    
        public virtual string Description
        {
            get;
            set;
        }
    
        public virtual string Subject
        {
            get;
            set;
        }
    
        public virtual string Body
        {
            get;
            set;
        }
    
        public virtual string ToAssignees
        {
            get;
            set;
        }
    
        public virtual string CCAssignees
        {
            get;
            set;
        }
    
        public virtual string BCCAssignees
        {
            get;
            set;
        }
    
        public virtual string FromAddress
        {
            get;
            set;
        }
    
        public virtual bool EmailIsDataSpecific
        {
            get;
            set;
        }

        #endregion
        #region Navigation Properties
    
        public virtual ETLImportDefinition ETLImportDefinition
        {
            get { return _eTLImportDefinition; }
            set
            {
                if (!ReferenceEquals(_eTLImportDefinition, value))
                {
                    var previousValue = _eTLImportDefinition;
                    _eTLImportDefinition = value;
                    FixupETLImportDefinition(previousValue);
                }
            }
        }
        private ETLImportDefinition _eTLImportDefinition;

        #endregion
        #region Association Fixup
    
        private void FixupETLImportDefinition(ETLImportDefinition previousValue)
        {
            if (previousValue != null && previousValue.ETLImportEmails.Contains(this))
            {
                previousValue.ETLImportEmails.Remove(this);
            }
    
            if (ETLImportDefinition != null)
            {
                if (!ETLImportDefinition.ETLImportEmails.Contains(this))
                {
                    ETLImportDefinition.ETLImportEmails.Add(this);
                }
                if (ETLImportGUID != ETLImportDefinition.ETLImportGUID)
                {
                    ETLImportGUID = ETLImportDefinition.ETLImportGUID;
                }
            }
        }

        #endregion
    }
}
